spring:
  application:
    name: "@app-name@"
    version: "@app-version@"
    description: "@app-description@"
    base-url: ${BASE_URL}:${server.port}${server.servlet.context-path}
  data:
    mongodb:
      host: localhost
      port: 27017
      username: ${USERNAME_MONGO_DB}
      password: ${PASSWORD_MONGO_DB}
      database: ${DB_MONGO_DB}
      authentication-database: ${AUTH_DB_MONGO_DB}
      auto-index-creation: true
  ai:
    deepseek:
      api-key: ${DEEP_SEEK_API_KEY}
      chat:
        options:
          temperature: 0.0
  mail:
    host: ${HOST_SRV_MAIL}
    port: ${PORT_SRV_MAIL}
    username: ${USERNAME_SRV_MAIL}
    password: ${PASSWORD_SRV_MAIL}
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true

  contexts:
    security:
      jwt:
        secret: ${SECRET_JWT}
        expiration:
          millis: 3600000
    api:
      key:
        evaluation: ${API_EVALUATION_KEY}
        creatorContent: ${API_CREATOR_CONTENT_KEY}
    support:
      email: ${CONTEXTS_SUPPORT_EMAIL}
      whatsapp: ${CONTEXTS_SUPPORT_WHATSAPP}
      linkDoc: ${CONTEXTS_SUPPORT_DOC}

server:
  servlet:
    context-path: "@app-base-path@"
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
  contacts:
    site: "@contact-site@"
    name: "@contact-name@"
    email: "@contact-email@"
  docs:
    doc: "@docs-doc@"
    doc-name: "@docs-doc-name@"
    license: "@docs-license@"
    license-name: "@docs-license-name@"
    term: "@docs-term@"

